[package]
name = "man-hours"
version = "0.1.0"
authors = ["Jesse Millar <jesse.millar@microsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "man-hours"
path = "main.rs"
